"""
Django settings for MYLIFE project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%bi8gi4p(qfcle&hawhi_13s6xvbtem*z6pn3w#)!!al@vw8c)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'ServiceLinebot',
    'ServiceWebsite',
    'ServiceWebsite_Vendor',
    'ServiceWebsite_Shop',
    'ServiceWebsite_Customer',
    
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.line',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MYLIFE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ServiceWebsite_Shop.context_processors.menu_categories',
                'ServiceWebsite_Shop.context_processors.cart_cash',
                'ServiceWebsite_Shop.context_processors.cart_bouns',
                'ServiceWebsite_Shop.context_processors.social_accounts_data',
                'ServiceWebsite_Shop.context_processors.is_vendor_mamber',
            ],
        },
    },
]

WSGI_APPLICATION = 'MYLIFE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  #PostgreSQL
        'NAME': 'd8oo0q861s8lug',  #資料庫名稱
        'USER': 'pulatvvotdpdav',  #資料庫帳號
        'PASSWORD': 'ed65126e3d21c68541ceca61a093b9b649d2c2c9d2e9e77acbcb22f62ececc24',  #資料庫密碼
        'HOST': 'ec2-3-223-242-224.compute-1.amazonaws.com',  #Server(伺服器)位址
        'PORT': '5432'  #PostgreSQL Port號
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',  #PostgreSQL
#         'NAME': '330228-2',  #資料庫名稱
#         'USER': 'postgres',  #資料庫帳號
#         'PASSWORD': '33mylife',  #資料庫密碼
#         'HOST': 'localhost',  #Server(伺服器)位址
#         'PORT': '5432'  #PostgreSQL Port號
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATICFILES_DIRS = [os.path.join(BASE_DIR,  'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_root')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_AGE = 86400 # Day in Seconds
SESSION_SERIALIZER = 'django.contrib.sessions.serializers' + '.PickleSerializer'
CASH_CART_SESSION_ID = 'cash_cart'
BOUNS_CART_SESSION_ID = 'bouns_cart'
ALL_CART_SESSION_ID = 'all_cart'
# LineBot Config
LINE_CHANNEL_ACCESS_TOKEN = 'oM/WrI1Q+PfZtofamXnfOSXIcFJAKLsr+Stw8/sXyoeZoMm3cOvBYjK4NG4P9Cnfv57/3EXlTAQJTsL0/gG+6TEoO1NfPLWX7cFhtJKtFSnB/yBBvlINNxJbRN/AZGhCREW7VKhIK8K5iBPOjupHvgdB04t89/1O/w1cDnyilFU='
LINE_CHANNEL_SECRET = '681fce3c00977d0d0563de3fe745bba0'

# SimpleUI Config
# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False 
SIMPLEUI_ANALYSIS = False 

# django_allauth Config 
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 2

SOCIALACCOUNT_PROVIDERS={
    "line":{
        "SCOPE": [
            "profile",
            "openid",
            "email"
        ]
    }
}

# 是否需要驗證郵箱
ACCOUNT_EMAIL_VERIFICATION = 'none'
# 社群帳號登入是否需要驗證郵箱
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
# 帳號登陸方法
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'

# Skip Django Allauth " You are about to sign in using a third party account" page
SOCIALACCOUNT_LOGIN_ON_GET=True
# ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_LOGOUT_ON_GET = True
# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'