# Generated by Django 4.0.6 on 2023-03-02 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('A', 'A級店家'), ('B', 'B級店家')], default='A', max_length=6)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_boss', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='vendor_emp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '供應商',
                'verbose_name_plural': '供應商',
                'ordering': ['name'],
            },
        ),
    ]
